import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Photon Engine Test - German',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="h-screen flex items-center justify-center m-0 p-0">{children}</body>
    </html>
  )
}
